services:
  - type: web
    name: moinst
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        sync: false
      - key: UPLOAD_DIR
        value: ./upload
      - key: NEXT_PUBLIC_GEMINI_API_KEYS
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_API_KEYS
        sync: false
      - key: NODE_VERSION
        value: 20.18.0
